# Numpy

In [1]:
import numpy as np

In [2]:
np.__version__

'1.26.4'

# Creating Arrays

In [3]:
my_list = [0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [4]:
type(my_list)

list

In [5]:
arr=np.array(my_list) #to convert list to array

In [6]:
arr

array([0, 1, 2, 3, 4, 5])

In [7]:
type(arr)

numpy.ndarray

In [8]:
type(my_list)

list

In [10]:
np.arange(15) #end index is n-1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [11]:
np.arange(3.0)

array([0., 1., 2.])

In [12]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [14]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [15]:
np.arange(20,10) #1st arg< 2nd arg

array([], dtype=int32)

In [16]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [17]:
np.arange(-16,10)

array([-16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,
        -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [18]:
np.arange(-20,-10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11])

In [23]:
ar=np.arange(-30,20)
ar

array([-30, -29, -28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18,
       -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,
        -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,
         9,  10,  11,  12,  13,  14,  15,  16,  17,  18,  19])

In [22]:
np.arange(10,10)

array([], dtype=int32)

In [24]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [26]:
np.arange(50,100,5)

array([50, 55, 60, 65, 70, 75, 80, 85, 90, 95])

In [27]:
np.zeros(5) # parameter tunning

array([0., 0., 0., 0., 0.])

In [28]:
np.zeros(5, dtype=int) #hyperparameter tuinning

array([0, 0, 0, 0, 0])

In [33]:
np.zeros((10,10)) #parameter

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [32]:
np.zeros((10,10),dtype=int) #hyperparameter

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [37]:
np.zeros((2,2,1),dtype=int)

array([[[0],
        [0]],

       [[0],
        [0]]])

In [42]:
zero=np.zeros([2,2])
type(zero)

numpy.ndarray

In [44]:
np.zeros((2,20))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.]])

In [47]:
n=(6,7)
n1=(6,8)
print(np.zeros(n)) #parameter tunning
print(np.zeros(n1))

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [52]:
print(np.zeros(n1,dtype=int)) #hyperparameter tunning

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


In [53]:
np.ones(4)

array([1., 1., 1., 1.])

In [56]:
np.ones(n) #6rows and 7 columns

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [4]:
import numpy as np
np.__version__

'1.26.4'

In [5]:
np.ones((5,6),dtype=int)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [6]:
range(5)

range(0, 5)

In [7]:
r= range(5)
r

range(0, 5)

In [8]:
for i in r:
    print(i)

0
1
2
3
4


In [9]:
list(range(5))

[0, 1, 2, 3, 4]

In [10]:
range(1,10)

range(1, 10)

In [11]:
list(range(1,10))

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [12]:
list(range(1,10,3))

[1, 4, 7]

In [14]:
y= list(range(12))
y

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [15]:
rand(3,2)

NameError: name 'rand' is not defined

In [16]:
ran(3,2)
random.rand(3,2)

NameError: name 'ran' is not defined

In [17]:
np.random.rand(4) # np is package , random is module, rand is function

array([0.97017169, 0.4750047 , 0.26226571, 0.01472414])

In [18]:
np.random.rand(5)

array([0.90913951, 0.16317088, 0.49263811, 0.75428087, 0.64970797])

In [19]:
np.random.rand(2,4)

array([[0.66271714, 0.50918557, 0.31048259, 0.49013555],
       [0.26714101, 0.57733095, 0.64961576, 0.40404945]])

In [20]:
np.random.randint(2,4) # any value btn 2 and 4 means 2 or 3

3

In [21]:
np.random.randint(2,4)

2

In [22]:
np.random.randint(0,1)

0

In [23]:
np.random.randint(1,2,3) # generate 3 numbers btn 1 and 2

array([1, 1, 1])

In [24]:
np.random.randint(1,3,4)

array([1, 2, 1, 1])

In [25]:
np.random.randint(1,3,4)

array([2, 1, 2, 1])

In [27]:
np.arange(1,11).reshape(5,2) #converted 5 rowa and 2 columns

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [28]:
np.random.randint(10,40,(10,10)) #generate the element 10 to 30 with 4*4 matrix

array([[33, 25, 27, 11, 16, 38, 26, 11, 26, 30],
       [27, 11, 38, 24, 21, 21, 14, 29, 12, 33],
       [36, 26, 21, 19, 35, 30, 34, 31, 30, 24],
       [35, 18, 36, 25, 34, 33, 13, 11, 20, 12],
       [20, 20, 37, 35, 35, 14, 29, 18, 14, 29],
       [20, 11, 22, 34, 36, 35, 36, 25, 39, 35],
       [37, 38, 27, 38, 17, 11, 29, 17, 19, 21],
       [15, 13, 14, 21, 28, 12, 16, 39, 15, 32],
       [18, 22, 35, 20, 13, 11, 30, 31, 12, 23],
       [34, 31, 26, 37, 16, 14, 14, 27, 15, 10]])

In [32]:
b= np.random.randint(10,20,(5,4))
b

array([[13, 18, 14, 15],
       [18, 19, 17, 16],
       [16, 10, 17, 19],
       [14, 12, 14, 10],
       [15, 11, 19, 14]])

In [30]:
type(b)

numpy.ndarray

In [33]:
b


array([[13, 18, 14, 15],
       [18, 19, 17, 16],
       [16, 10, 17, 19],
       [14, 12, 14, 10],
       [15, 11, 19, 14]])

In [34]:
b= np.random.randint(10,20,(5,4))
b

array([[16, 12, 12, 11],
       [16, 19, 13, 14],
       [10, 17, 10, 11],
       [14, 17, 19, 16],
       [11, 10, 18, 19]])

In [35]:
b[1:3]

array([[16, 19, 13, 14],
       [10, 17, 10, 11]])

In [36]:
b

array([[16, 12, 12, 11],
       [16, 19, 13, 14],
       [10, 17, 10, 11],
       [14, 17, 19, 16],
       [11, 10, 18, 19]])

In [37]:
b[1,3]

14

In [38]:
b[2:3]

array([[10, 17, 10, 11]])

In [39]:
b

array([[16, 12, 12, 11],
       [16, 19, 13, 14],
       [10, 17, 10, 11],
       [14, 17, 19, 16],
       [11, 10, 18, 19]])

In [41]:
b[0:-1]

array([[16, 12, 12, 11],
       [16, 19, 13, 14],
       [10, 17, 10, 11],
       [14, 17, 19, 16]])

In [42]:
b[0,2]

12

In [43]:
b

array([[16, 12, 12, 11],
       [16, 19, 13, 14],
       [10, 17, 10, 11],
       [14, 17, 19, 16],
       [11, 10, 18, 19]])

In [44]:
b[-5,-3]

12

In [45]:
b[-4:2]

array([[16, 19, 13, 14]])

In [46]:
a=np.random.randint(10,20,5)

In [48]:
a

array([19, 18, 11, 16, 19])

In [53]:
arr
array([0,1,2,3,4,5])
arr2=np.random.randint(0,100,(10,10))
arr2

NameError: name 'arr' is not defined

In [54]:
array([0,1,2,3,4,5])

NameError: name 'array' is not defined

In [57]:
arr

NameError: name 'arr' is not defined

In [56]:
array([0,1,2,3,4,5])
arr.reshape(2,3)

NameError: name 'array' is not defined

In [62]:
mat=np.arange(0,100).reshape(10,10)

In [63]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [64]:
row=4
col=5

In [65]:
row

4

In [66]:
col

5

In [67]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [68]:
mat[row,col]

45

In [69]:
mat[4,5]

45

In [70]:
col=6

In [71]:
mat[6]

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [72]:
mat[:,col] #with slices how to print columns

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [73]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [74]:
mat[row,:]

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [75]:
mat[:,col]

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [76]:
mat[:,-1]

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])

In [77]:
mat[0:10]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [79]:
mat[0:10:3]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [81]:
mat[2:6,2:4]

array([[22, 23],
       [32, 33],
       [42, 43],
       [52, 53]])

In [82]:
mat[1:2,2:4]

array([[12, 13]])

In [83]:
mat


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [84]:
mat[2:3,2:3]

array([[22]])

In [85]:
id(mat)

1499484947920

In [86]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

mat

In [87]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [88]:
mat < 50

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [89]:
mat[mat>50]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [90]:
mat==50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [ True, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [91]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

# Identity

In [2]:
import numpy as np

In [3]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [5]:
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

# Array Attributes

In [8]:
a1=np.arange(10) #1D
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
a2=np.arange(12,dtype=float).reshape(3,4) #matrix
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [13]:
a3=np.arange(8).reshape(2,2,2) #3D ----> Tensor
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

# ndim

In [ ]:
# To findout given arrays number of dimensions

In [14]:
a1.ndim

1

In [15]:
a2.ndim

2

In [16]:
a3.ndim

3

# Shape

In [17]:
a1.shape # 1D array has 10 elements

(10,)

In [18]:
a2.shape # 3 rows and 4 columns

(3, 4)

In [19]:
a3.shape #first, 2 says it consists 2d arrays 2,2 gives no. of rows and columns

(2, 2, 2)

# Size

In [ ]:
#givess number of items

In [20]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [21]:
a3.size # it has 8 items like shape 2,2,2=8

8

In [22]:
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [23]:
a2.size

12

# Item size

In [ ]:
# memory occupied by item

In [24]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
a1.itemsize #bytes

4

In [26]:
a2.itemsize # integer 64 gives =8bytes

8

In [27]:
a3.itemsize

4

In [28]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

# dtype

In [ ]:
#gives the data type of the item

In [29]:
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int32


# Changing data Type

In [31]:
#astype
x=np.array([33,22,2.5])
x

array([33. , 22. ,  2.5])

In [32]:
x.astype(int)

array([33, 22,  2])

# Array operations

In [35]:
z1=np.arange(12).reshape(3,4)
z2= np.arange(12,24).reshape(3,4)

In [36]:
z1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [37]:
z2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])